spring.application.name=storm.event
######################## HTTP ########################
okhttp.connect-timeout-ms=5000
okhttp.read-timeout-ms=10000
okhttp.write-timeout-ms=10000
okhttp.call-timeout-ms=0
okhttp.retry-on-connection-failure=true
okhttp.max-idle-connections=5
okhttp.keep-alive-minutes=5
