-- V1: схема storm и все таблицы.
--
-- Схема применяется одной миграцией осознанно: до V1 ни одна миграция
-- не была применена ни к одной базе, поэтому история схемы начинается здесь
-- (ADR-040). Вторичные индексы вынесены в V3, начальные данные - в V2,
-- чтобы порядок применения не зависел от «случайных» правок DDL.
--
-- Соглашения (ADR-014):
--   * имена таблиц и колонок - snake_case;
--   * PK технических сущностей - bigint identity;
--   * request_id / session_id - uuid в отдельных колонках;
--   * временные метки - timestamptz (технически UTC, ADR-016);
--   * идентификаторы источников - varchar с COLLATE "C" (быстрое сравнение).

CREATE SCHEMA IF NOT EXISTS storm;

-- =====================================================
-- session: диалог пользователя, TTL задаёт приложение (ADR-038)
-- expires_at вычисляется приложением и продлевается каждым обращением
-- (ADR-VL-02): выражение last_access_at + ttl * interval нельзя заиндексировать,
-- timestamptz + interval зависит от таймзоны сессии и не иммутабелен.
-- =====================================================
CREATE TABLE storm.session (
    id              UUID PRIMARY KEY,
    intent          JSONB,
    last_access_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at      TIMESTAMPTZ NOT NULL DEFAULT NOW() + INTERVAL '15 minutes',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ttl_seconds     INT NOT NULL DEFAULT 900 CHECK (ttl_seconds > 0),
    state           VARCHAR(16) NOT NULL DEFAULT 'NEW' CHECK (state IN ('NEW', 'ACTIVE', 'CLOSED'))
);

-- =====================================================
-- session_message: реплики диалога, контекст для LLM (ADR-VL-02)
-- =====================================================
CREATE TABLE storm.session_message (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id      UUID NOT NULL REFERENCES storm.session (id) ON DELETE CASCADE,
    role            VARCHAR(8) NOT NULL CHECK (role IN ('user', 'agent')),
    kind            VARCHAR(16) NOT NULL CHECK (kind IN ('search', 'refine', 'answer', 'system')),
    text            TEXT NOT NULL,
    request_id      UUID,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =====================================================
-- source_state: ручное состояние источников (ADR-VL-04, circuit breaker не делаем)
-- =====================================================
CREATE TABLE storm.source_state (
    source          VARCHAR(32) COLLATE "C" PRIMARY KEY,
    enabled         BOOLEAN NOT NULL DEFAULT TRUE,
    draining        BOOLEAN NOT NULL DEFAULT FALSE,
    ramp_until      TIMESTAMPTZ,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =====================================================
-- cached_result: кэш нормализованных офферов источника (ADR-042)
-- =====================================================
CREATE TABLE storm.cached_result (
    cache_key       VARCHAR(255) PRIMARY KEY,
    source          VARCHAR(32) COLLATE "C" NOT NULL,
    domain          VARCHAR(16) COLLATE "C" NOT NULL,
    payload_json    JSONB NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at      TIMESTAMPTZ NOT NULL,
    stale           BOOLEAN NOT NULL DEFAULT FALSE,
    CHECK (expires_at > created_at)
);

-- =====================================================
-- idempotency: окно дедупликации ручного ретрая (ADR-VL-15)
-- =====================================================
CREATE TABLE storm.idempotency (
    request_id      UUID PRIMARY KEY,
    response_json   JSONB,
    session_id      UUID,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at      TIMESTAMPTZ NOT NULL
);

-- =====================================================
-- request_log: аудит запросов, партиционирован по месяцам (ADR-033)
-- PK обязан включать ключ партиционирования.
-- =====================================================
CREATE TABLE storm.request_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    request_id      UUID NOT NULL,
    -- Аудит переживает удаление сессии: ссылка обнуляется, строка остаётся.
    session_id      UUID REFERENCES storm.session (id) ON DELETE SET NULL,
    text            TEXT,
    intent_json     JSONB,
    status          VARCHAR(16) NOT NULL CHECK (status IN ('OK', 'ERROR')),
    duration_ms     INT CHECK (duration_ms IS NULL OR duration_ms >= 0),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

CREATE TABLE storm.request_log_default PARTITION OF storm.request_log DEFAULT;

-- =====================================================
-- source_error_log: ошибки источников, партиционированы так же
-- =====================================================
CREATE TABLE storm.source_error_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    request_id      UUID NOT NULL,
    source          VARCHAR(32) COLLATE "C" NOT NULL,
    code            VARCHAR(64) COLLATE "C" NOT NULL,
    message         TEXT,
    latency_ms      INT CHECK (latency_ms IS NULL OR latency_ms >= 0),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

CREATE TABLE storm.source_error_log_default PARTITION OF storm.source_error_log DEFAULT;

-- =====================================================
-- stats_source_hourly: агрегаты ошибок по UTC-часам (ADR-035)
-- =====================================================
CREATE TABLE storm.stats_source_hourly (
    hour            TIMESTAMPTZ NOT NULL,
    source          VARCHAR(32) COLLATE "C" NOT NULL,
    code            VARCHAR(64) COLLATE "C" NOT NULL,
    count           INT NOT NULL DEFAULT 0 CHECK (count >= 0),
    PRIMARY KEY (hour, source, code)
) PARTITION BY RANGE (hour);

CREATE TABLE storm.stats_source_hourly_default PARTITION OF storm.stats_source_hourly DEFAULT;
