-- V1: Create storm schema and core tables
-- Schema for session, session_message, source_state, cached_result, idempotency, request_log, source_error_log, stats_source_hourly

-- Create schema
CREATE SCHEMA IF NOT EXISTS storm;

-- Set search path
SET search_path TO storm, public;

-- =====================================================
-- session: хранение диалогов пользователя
-- =====================================================
CREATE TABLE IF NOT EXISTS storm.session (
    id              UUID PRIMARY KEY,
    intent          JSONB,
    last_access_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ttl_seconds     INT NOT NULL DEFAULT 900,
    state           VARCHAR(16) NOT NULL DEFAULT 'NEW'
);

CREATE INDEX IF NOT EXISTS idx_session_created_at ON storm.session (created_at);
CREATE INDEX IF NOT EXISTS idx_session_state ON storm.session (state);

-- =====================================================
-- session_message: сообщения диалога (контекст для LLM)
-- =====================================================
CREATE TABLE IF NOT EXISTS storm.session_message (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id      UUID NOT NULL REFERENCES storm.session(id) ON DELETE CASCADE,
    role            VARCHAR(8) NOT NULL,      -- 'user' | 'agent'
    kind            VARCHAR(16) NOT NULL,     -- 'search' | 'refine' | 'answer' | 'system'
    text            TEXT NOT NULL,
    request_id      UUID,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_session_message_session_created ON storm.session_message (session_id, created_at);

-- =====================================================
-- source_state: состояние источников (вкл/выкл, дренирование)
-- =====================================================
CREATE TABLE IF NOT EXISTS storm.source_state (
    source          VARCHAR(32) PRIMARY KEY,
    enabled         BOOLEAN NOT NULL DEFAULT TRUE,
    draining        BOOLEAN NOT NULL DEFAULT FALSE,
    ramp_until      TIMESTAMPTZ,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =====================================================
-- cached_result: кэш ответов источников
-- =====================================================
CREATE TABLE IF NOT EXISTS storm.cached_result (
    cache_key       VARCHAR(255) PRIMARY KEY,
    source          VARCHAR(32) NOT NULL,
    domain          VARCHAR(16) NOT NULL,
    payload_json    JSONB NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at      TIMESTAMPTZ NOT NULL,
    stale           BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_cached_result_expires_at ON storm.cached_result (expires_at);
CREATE INDEX IF NOT EXISTS idx_cached_result_source_domain ON storm.cached_result (source, domain);

-- =====================================================
-- idempotency: идемпотентность запросов
-- =====================================================
CREATE TABLE IF NOT EXISTS storm.idempotency (
    request_id      UUID PRIMARY KEY,
    response_json   JSONB,
    session_id      UUID,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at      TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_idempotency_expires_at ON storm.idempotency (expires_at);

-- =====================================================
-- request_log: аудит запросов
-- =====================================================
CREATE TABLE IF NOT EXISTS storm.request_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id      UUID NOT NULL,
    session_id      UUID,
    text            VARCHAR(2000),
    intent_json     JSONB,
    status          VARCHAR(16) NOT NULL,
    duration_ms     INT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_request_log_created_at ON storm.request_log (created_at);
CREATE INDEX IF NOT EXISTS idx_request_log_session_id ON storm.request_log (session_id);

-- =====================================================
-- source_error_log: логи ошибок источников
-- =====================================================
CREATE TABLE IF NOT EXISTS storm.source_error_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id      UUID NOT NULL,
    source          VARCHAR(32) NOT NULL,
    code            VARCHAR(64) NOT NULL,
    message         VARCHAR(1000),
    latency_ms      INT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_source_error_log_created_at ON storm.source_error_log (created_at);
CREATE INDEX IF NOT EXISTS idx_source_error_log_source_code ON storm.source_error_log (source, code);

-- =====================================================
-- stats_source_hourly: агрегаты ошибок по часам
-- =====================================================
CREATE TABLE IF NOT EXISTS storm.stats_source_hourly (
    hour            TIMESTAMPTZ NOT NULL,
    source          VARCHAR(32) NOT NULL,
    code            VARCHAR(64) NOT NULL,
    count           INT NOT NULL DEFAULT 0,
    PRIMARY KEY (hour, source, code)
);

-- =====================================================
-- Initial data for source_state
-- =====================================================
INSERT INTO storm.source_state (source, enabled, draining, updated_at) VALUES
    ('atlasbus', TRUE, FALSE, NOW()),
    ('ticketbus', TRUE, FALSE, NOW()),
    ('bzd', TRUE, FALSE, NOW()),
    ('ticketpro', TRUE, FALSE, NOW()),
    ('belhotel', TRUE, FALSE, NOW())
ON CONFLICT (source) DO NOTHING;